<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>be60b1d0-fb57-4f75-946a-dff1fe0684e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.47.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.47.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelAgency.ServiceDefaults\TravelAgency.ServiceDefaults.csproj" />
    <ProjectReference Include="..\TravelAgency.Shared\TravelAgency.Shared.csproj" />
  </ItemGroup>

</Project>
